### ISSUE TITLE
Primitive data type are not retained during update

### ISSUE THREAD

**Issue by kavya-joshi** [hummingwave/waveorm#1]
Primitive data type like int, long, double, boolean are not retained when we do update of the row using the where clause.

Eg : Employee employee = new Employee();
       employee.setName("Chaitra Kavya");
       employee.update("empID = ?", new String[]{"027"});

If suppose employee object has a field called salary of data type int, which was previously set during save, will be lost during this update.

**Comment by ChaitraKavya** [comment]
If the record contains primitive data types to retain it's value, before updating the record, fetch the record and then update the record, else it will set the value of primitive data types to it's default values.
